name: Push Workflow
on: workflow_dispatch
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Git Checkout
     uses: actions/checkout@v3
   - name: Install dependencies
     run: npm install
   - name: Build Code
     run: npm run build
